# Path: backend/config/config-default.yaml

database:
  mongodb:
    host: localhost
    port: 27017
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
    db_name: limana

logging:
  level: DEBUG
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  output: stdout
