# Path: backend/config/config-default.yaml
server:
  host: localhost
  port: 8080

database:
  mongodb:
    host: localhost
    port: 27017
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
    db_name: limana

  sqlite:
    dbloc: ./runtime/sqlite/database.db
    tables:
      auth: _tbl_auth
      session: _tbl_session

logging:
  level: DEBUG
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  output: stdout

authentication:
  cleanup_interval: 1d
  token_alive: 3d
