# Path: backend/config/config-default.yaml
server:
  host: localhost
  port: 8080

database:
  sqlite:
    dbloc: ./runtime/sqlite/database.db
    tables:
      auth: _tbl_auth
      session: _tbl_session
      book: _tbl_book

logging:
  level: DEBUG
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  output: stdout

authentication:
  cleanup_interval: 1d
  token_alive: 3d

library:
  borrow_time: 10d
